name: Publish Project

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Git Semantic Version
        id: version
        # You may pin to the exact commit or the version.
        # uses: PaulHatch/semantic-version@a8f8f59fd7f0625188492e945240f12d7ad2dca3
        uses: PaulHatch/semantic-version@v5.4.0
      - name: Cancel if Unchanged
        if: ${{ ! steps.version.outputs.changed }}
        run: |
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Override new version
        run: |
          echo ${{ steps.version.outputs.version }} > scripto.VERSION
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build Project
        run: |
          python -m build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: dist-${{ matrix.python-version }}
          path: dist/*
          if-no-files-found: error
          retention-days: 10

  publish:
    runs-on: ubuntu-latest
    env:
      pub_token: ${{ secrets.PYPI_API_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
    needs: [ build ]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.0
        with:
          name: dist-${{ matrix.python-version }}
          pattern: dist-${{ matrix.python-version }}
          # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
          path: dist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ env.pub_token }}
